### ISSUE TITLE
I cannot download using the magnet link

### ISSUE THREAD

**Issue by aryannxroot** [iw4p/torrentp#14]
Whenever I try to download using the magnet link the interpreter shows this error 
: Enable tracemalloc to get the object allocation traceback

Please help me here!!!!!!!!!!!!!
![Screenshot 2024-03-13 014729](https://github.com/iw4p/torrentp/assets/69583042/a41bd05e-6eac-4c8e-9d82-3351eef8cb45)

**Comment by iw4p** [comment]
Hi, can you please install previous versions? Previous ones does not have async await.
Older versions: https://pypi.org/project/torrentp/0.1.6/

Install it like:
pip install torrentp==0.1.6

**Comment by ufoptg** [comment]
> Whenever I try to download using the magnet link the interpreter shows this error : Enable tracemalloc to get the object allocation traceback
> 
> Please help me here!!!!!!!!!!!!! ![Screenshot 2024-03-13 014729](https://private-user-images.githubusercontent.com/69583042/312225053-a41bd05e-6eac-4c8e-9d82-3351eef8cb45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNzc2MjksIm5iZiI6MTcxMzM3NzMyOSwicGF0aCI6Ii82OTU4MzA0Mi8zMTIyMjUwNTMtYTQxYmQwNWUtNmVhYy00YzhlLTlkODItMzM1MWVlZjhjYjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE4MDg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkYjljMzcwZDJkOTU2MTBmOTcwNjM1YTI3M2E5NDgxZTAwNjdlNWU1N2YwZTE4MjA2ZmEyZDE1N2U5NTM1OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d468vqRa2Q_U2ks58a0VIE9LvQp7lfDl-VYCdKMRNcY)

its because you are not awaiting the downloader

you have defined an async function called "downloadtorrent"

then on the second last line your not awaiting it..

so above print("Completed") you need to change it from _downloadtorrent(torrent_file)_ **TO** _await downloadtorrent(torrent_file)_

**Comment by ufoptg** [comment]
any time you define a function async you must await it or use it asynchronously
