### ISSUE TITLE
no libtorrent found but i have installed it 

### ISSUE THREAD

**Issue by ahmadkarimi4** [iw4p/torrentp#2]
![image](https://user-images.githubusercontent.com/117602367/201883575-a907468a-c827-4757-a8b8-d9a4f7b8a36c.png)

how do i fix it?

**Comment by iw4p** [comment]
DLL? Do you want to use it on windows?

**Comment by ahmadkarimi4** [comment]
yes we cant??

**Comment by iw4p** [comment]
I think it's ok, but I can't test it on Windows right now. I suggest you to use it on Google Colab, and download your file from your Google Drive.

**Comment by ahmadkarimi4** [comment]
oh ok thanks i tried it on pythonanywhere and it works fine I think best is to run it on a linux environment

**Comment by iw4p** [comment]
Yes, exactly.
