### ISSUE TITLE
How to use proxy to download

### ISSUE THREAD

**Issue by HarryHsing** [iw4p/torrentp#3]
Thank you very much for your great work!

I wonder if I can download the file via a proxy?

**Comment by iw4p** [comment]
Hello,
You're welcome!
You need to download a file when proxy is enabled? You can set it in your terminal session like this:
HTTPS_PROXY=IP:PORT

**Comment by HarryHsing** [comment]
> Hello, You're welcome! You need to download a file when proxy is enabled? You can set it in your terminal session like this: HTTPS_PROXY=IP:PORT

Got it! Thanks a lot!
