### ISSUE TITLE
limit dl and ul speeds

### ISSUE THREAD

**Issue by erdincsk** [iw4p/torrentp#4]
is it possible to limit download and upload speeds with torrentp?

thanks.

**Comment by iw4p** [comment]
Hello,
I added this feature for you. Please uninstall and install the latest version which is "0.1.6" and give me feedback.
I also added some notes on README to see an example for its syntax.

**Comment by erdincsk** [comment]
hello,

i tested and works great.

thanks a lot

**Comment by iw4p** [comment]
You're welcome!
