### ISSUE TITLE
Pip dependency resolution

### ISSUE THREAD

**Issue by CobraCabbe-CTRL** [iw4p/torrentp#6]
When downloading the package using `pip install torrentp` the terminal spits out this: 
![image](https://github.com/iw4p/torrentp/assets/92878402/1dbb43df-e4d0-41b2-8b62-aeede5a23e6e)
None of the fixes work and it seems that i need to install libtorrent before this

**Comment by iw4p** [comment]
Hi, It is fine on Colab.

<img width="912" alt="Screenshot 2023-07-14 at 10 22 56 PM" src="https://github.com/iw4p/torrentp/assets/30632761/eb0f7ed3-ae64-4349-a089-c1d9e6c89a97">


I suggest you to choose the .whl based on your OS from [here](https://pypi.org/project/libtorrent/#files)
And you can install it with the URL of .whl file like this:

`pip install https://files.pythonhosted.org/packages/5e/36/25edad77d9d66ad58bc3bacc37a1c475a72cb2fe73c64c4378b1680081aa/libtorrent-2.0.9-cp310-cp310-win_amd64.whl
`

You have to be careful about the `cp**` for example `cp37` means python3.7

**Comment by iw4p** [comment]
Also, another option is downgrading your python version.

**Comment by RaviRCoder** [comment]
it's the issue with libtorrent issue in windows this same error shows me and i can't find any solution or other way but it works with **Linux**

**Comment by iw4p** [comment]
> it's the issue with libtorrent issue in windows this same error shows me and i can't find any solution or other way but it works with **Linux**

LONG LIVE LINUX
