### ISSUE TITLE
Download stuck on "downloading_metadata"

### ISSUE THREAD

**Issue by Jagname** [iw4p/torrentp#7]
![image](https://github.com/iw4p/torrentp/assets/104325330/23ae5012-5e83-4c1a-baa1-5bf8d1622026)

The first time it worked but not anymore.

Thanks for your help!

**Comment by iw4p** [comment]
Hi.
The reason can be your file/magnet-link.
![Screenshot 2023-08-01 at 3 37 59 PM](https://github.com/iw4p/torrentp/assets/30632761/377d0af6-2afb-4647-b16c-6e725c09d641)

I tested and it was fine.

**Comment by RaviRCoder** [comment]
i think it's the issue with Magnet link, some are very slow 😔

**Comment by iw4p** [comment]
Yes, It really depends on the magnet link and the ratio of seeder and leecher.
